version: "3.4"

services:
  op-connect-api:
    image: 1password/connect-api:latest
    ports:
      - "8080:8080"
    volumes:
      - "~/Applications/docker-data/1password/data/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "~/Applications/docker-data/1password/data:/home/opuser/.op/data"
  op-connect-sync:
    image: 1password/connect-sync:latest
    ports:
      - "8081:8080"
    volumes:
      - "~/Applications/docker-data/1password/data/1password-credentials.json:/home/opuser/.op/1password-credentials.json"
      - "~/Applications/docker-data/1password/data:/home/opuser/.op/data"

volumes:
  data:
