services:
  hoppscotch:
    container_name: hoppscotch
    image: hoppscotch/hoppscotch
    restart: unless-stopped
    volumes:
      - ~/Applications/docker-data/hoppscotch/upload:/home/admin/upload
    ports:
      - ${FRONTEND_PORT}:3000
      - ${BACKEND_PORT}:3100
      - ${ADMIN_PORT}:3170
      - ${APP_PORT}:3200
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - HOPP_AIO_ALTERNATE_PORT=${HOPP_AIO_ALTERNATE_PORT}
      - DATA_ENCRYPTION_KEY=${DATA_ENCRYPTION_KEY}
      - WHITELISTED_ORIGINS=${WHITELISTED_ORIGINS}
      - VITE_BASE_URL=${VITE_BASE_URL}
      - VITE_SHORTCODE_BASE_URL=${VITE_SHORTCODE_BASE_URL}
      - VITE_ADMIN_URL=${VITE_ADMIN_URL}
      - VITE_BACKEND_GQL_URL=${VITE_BACKEND_GQL_URL}
      - VITE_BACKEND_WS_URL=${VITE_BACKEND_WS_URL}
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL}
      - ENABLE_SUBPATH_BASED_ACCESS=${ENABLE_SUBPATH_BASED_ACCESS}
    network_mode: bridge
    pull_policy: always
