services:
  vinet:
    container_name: mysql
    hostname: mysql
    image: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test123
    volumes:
      - ~/Applications/docker-data/vinet-mysql/data:/var/lib/mysql
