services:
  ngrok:
    container_name: ngrok
    hostname: ngrok
    image: ngrok/ngrok:latest
    restart: unless-stopped
    pull_policy: always
    network_mode: bridge
    ports:
      - 4040:4040
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ~/Applications/docker-data/ngrok/ngrok.yml:/etc/ngrok.yml