services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ~/Applications/docker-data/postgres:/var/lib/postgresql
    networks:
      - postgres_network
    ports:
      - 5432:5432
    pull_policy: always

networks:
  postgres_network:
    external: true