services:
  seq:
    container_name: seq
    hostname: seq
    image: datalust/seq
    restart: unless-stopped
    ports:
      - 53480:80
      - 53441:5341
    volumes:
      - ~/Applications/docker-data/seq/data:/data
    environment:
      - ACCEPT_EULA=Y
    network_mode: bridge
    pull_policy: always
